version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/sourdough-app/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(backend)"
    reviewers:
      - "cmollenbach"
    
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/sourdough-app/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(frontend)"
    reviewers:
      - "cmollenbach"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
