[build]
  command = "npm install --include=optional && npm run build:frontend"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20.18.1"
  NPM_VERSION = "10.8.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
